version: '3'
services:
  frontend-nginx:
    volumes:
      - ./frontend:/var/www/frontend
    build:
      context: ./docker/frontend/nginx
    ports:
      - "8888:80"
  frontend-nodejs:
    image: node:10.11-jessie
    volumes:
      - ./frontend:/var/www/frontend
    working_dir: /var/www/frontend
    tty: true

  backend-nginx:
    volumes:
      - ./backend:/var/www/backend
    build:
      context: ./docker/backend/nginx
    ports:
      - "8889:80"
    networks:
      - internal

  backend-php-fpm:
    volumes:
      - ./backend:/var/www/backend
    build:
      context: ./docker/backend/php-fpm
    environment:
      - "DB_HOST=mysql"
      - "DB_PORT=3306"
    networks:
      - internal

  backend-php-cli:
    volumes:
      - ./backend:/var/www/backend
    build:
      context: ./docker/backend/php-cli
    environment:
      - "DB_HOST=mysql"
      - "DB_PORT=3306"
    working_dir: /var/www/backend
    tty: true

  mysql:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=app"
    ports:
      - "33061:3306"
    volumes:
      - ./backend/storage/docker/mysql:/var/lib/mysql

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
